<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\{Foundation,School,Page,News,Statistic,Admission,Extracurricular};
class DatabaseSeeder extends Seeder {
 public function run():void {
 $published=['status'=>'published','published_at'=>'2026-01-01 00:00:00'];
 Foundation::firstOrCreate(['slug'=>'harapan-mulia'],[...$published,'title'=>'Yayasan Pendidikan Harapan Mulia','description'=>'Membangun generasi cerdas, berkarakter luhur, dan berdaya saing global melalui pendidikan holistik berlandaskan integritas.','data'=>['short_name'=>'Harapan Mulia','established_year'=>2005,'vision'=>'Pendidikan yang berakar pada nilai, tumbuh untuk masa depan.','mission'=>'Pembelajaran holistik; Karakter dan budi pekerti; Inovasi dan riset mandiri; Kepedulian sosial dan lingkungan.','history'=>'Didirikan pada 2005, kemudian membuka SD pada 2008, SMP pada 2013, dan SMA pada 2018.','chair_name'=>'Dr. H. Faisal Rahman, M.Ed.','chair_title'=>'Ketua Yayasan','chair_message'=>'Pendidikan adalah investasi paling bermakna untuk generasi yang belum kita lihat hari ini.','organization'=>['Ketua Yayasan'=>'Dr. H. Faisal Rahman, M.Ed.','Pengurus'=>'Dra. Hj. Maryam Kartini, M.Psi.','Pengelola Pendidikan'=>'Ir. Bambang Wicaksono, M.T.','Pengawas'=>'Dr. Nurul Izzati, M.Sc.'],'address'=>'Jl. Pendidikan No. 1, Cilandak, Jakarta Selatan 12430','email'=>'admin@harapanmulia.sch.id','phone'=>'+62 21 1234 5678','whatsapp'=>'6281234567890','maps_url'=>'https://maps.google.com/?q=Cilandak+Jakarta+Selatan','social_media'=>[]]]);
 $schools=[];
 foreach(['sd','smp','sma'] as $index=>$level){
  $schools[$level]=School::firstOrCreate(['slug'=>$level],[...$published,'title'=>strtoupper($level).' Harapan Mulia','sort_order'=>$index,'description'=>['Fondasi karakter dan pembelajaran menyenangkan.','Eksplorasi nalar dan kepemimpinan remaja.','Persiapan universitas, karier, dan kepemimpinan.'][$index],'data'=>['level'=>strtoupper($level),'established_year'=>[2008,2013,2018][$index],'vision'=>'Menumbuhkan nalar, karakter, dan kepedulian.','mission'=>'Belajar aktif, membangun karakter, dan berkarya untuk sesama.','curriculum'=>'Kurikulum Nasional dengan pembelajaran berbasis proyek dan pendidikan karakter.','principal_name'=>['Dra. Hj. Siti Aminah, M.Pd.','Bpk. Ahmad Fauzi, S.Pd., M.Ed.',''][$index],'address'=>'Kampus Harapan Mulia, Cilandak, Jakarta Selatan','email'=>$level.'@harapanmulia.sch.id','phone'=>'+62 21 1234 5678','whatsapp'=>'6281234567890']]);
  Admission::firstOrCreate(['slug'=>$level],[...$published,'school_id'=>$schools[$level]->id,'title'=>'PPDB '.strtoupper($level).' Harapan Mulia','description'=>'Informasi pendaftaran tahun ajaran baru.','data'=>['academic_year'=>'2026/2027','registration_start'=>'2026-01-01','registration_end'=>'2026-12-31','requirements'=>'Memenuhi usia jenjang pendidikan dan mengikuti asesmen sesuai ketentuan sekolah.','documents'=>'Akta kelahiran, kartu keluarga, pasfoto, serta rapor/ijazah jenjang sebelumnya bila diperlukan.','stages'=>"Pilih jenjang dan baca persyaratan\nHubungi admin atau isi formulir eksternal\nIkuti asesmen dan wawancara\nTerima pengumuman\nDaftar ulang",'publish_fees'=>false,'registration_fee'=>[450000,500000,550000][$index],'entrance_fee'=>[14500000,17500000,19500000][$index],'tuition_fee'=>[1400000,1650000,1850000][$index],'contact'=>'6281234567890','registration_url'=>'https://wa.me/6281234567890']]);
 }
 foreach(json_decode(file_get_contents(database_path('seeders/data/pages.json')),true) as $row){$row['school_id']=isset($schools[$row['school']??''])?$schools[$row['school']]->id:null;unset($row['school']);Page::firstOrCreate(['slug'=>$row['slug']],[...$row,...$published]);}
 foreach(json_decode(file_get_contents(database_path('seeders/data/entities.json')),true) as $model=>$rows){foreach($rows as $i=>$row){$level=$row['school'];unset($row['school']);$row['school_id']=$schools[$level]->id??null;$class='App\\Models\\'.$model;$record=$class::firstOrCreate(['slug'=>$row['slug']],[...$row,...$published,'content'=>$row['description'],'sort_order'=>$i]);if(method_exists($record,'schools'))$record->schools()->syncWithoutDetaching(collect($schools)->pluck('id')->all());}}
 $article=Page::where('slug','article')->first();
 News::firstOrCreate(['slug'=>'inquiry-adab'],[...$published,'title'=>'Menumbuhkan Sikap Inquiry & Adab: Mengapa Sains Harus Selaras dengan Ketajaman Empati Sosial','description'=>'Ketika kepintaran teknis perlu berjalan bersama karakter dan kepedulian.','content'=>implode("\n\n",array_filter($article->data['copy'],fn($text)=>mb_strlen($text)>140)),'image'=>array_values($article->data['images'])[0]??null,'data'=>['author'=>'Dr. H. Faisal Rahman, M.Ed.','category'=>'yayasan']]);
 foreach(['schools'=>['3','Unit Sekolah'],'students'=>['1.200+','Siswa'],'teachers'=>['80+','Tenaga Pendidik'],'experience'=>['20+','Tahun Pengalaman']] as $slug=>[$value,$label])Statistic::firstOrCreate(['slug'=>$slug],[...$published,'title'=>$label,'data'=>compact('value','label')]);
 foreach(['Basket','Pramuka','Coding Club','Tahfidz','Musik','Robotika'] as $i=>$title){$record=Extracurricular::firstOrCreate(['slug'=>\Illuminate\Support\Str::slug($title)],[...$published,'title'=>$title,'description'=>'Pengembangan minat, bakat, dan karakter melalui kegiatan '.$title.'.','sort_order'=>$i]);$record->schools()->syncWithoutDetaching(collect($schools)->pluck('id')->all());}
 }
}
