<form id="formulir" action="{{ route('inquiries.store') }}" method="post" class="space-y-4 rounded-2xl bg-white p-6 text-on-surface" x-data="{ type: '{{ old('type','contact') }}' }">
@csrf
<h2 class="font-serif text-2xl text-forest">Kirim Pesan & Jadwalkan Kunjungan</h2>
<label class="block text-sm font-semibold">Nama lengkap<input name="name" autocomplete="name" value="{{ old('name') }}" required maxlength="150" class="mt-2 w-full rounded-xl border-sage-border focus:border-forest focus:ring-forest"></label>
<div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-semibold">Email<input name="email" autocomplete="email" type="email" value="{{ old('email') }}" required class="mt-2 w-full rounded-xl border-sage-border focus:ring-forest"></label><label class="block text-sm font-semibold">WhatsApp / telepon<input name="phone" autocomplete="tel" type="tel" value="{{ old('phone') }}" maxlength="30" class="mt-2 w-full rounded-xl border-sage-border focus:ring-forest"></label></div>
<div class="grid gap-4 sm:grid-cols-2"><label class="block text-sm font-semibold">Tujuan<select name="school_id" class="mt-2 w-full rounded-xl border-sage-border"><option value="">Sekretariat Yayasan</option>@foreach($schools as $unit)<option value="{{ $unit->id }}" @selected(old('school_id')==$unit->id)>{{ $unit->title }}</option>@endforeach</select></label><label class="block text-sm font-semibold">Keperluan<select name="type" x-model="type" class="mt-2 w-full rounded-xl border-sage-border"><option value="contact">Informasi umum / PPDB</option><option value="tour">Kunjungan kampus</option></select></label></div>
<label x-cloak x-show="type === 'tour'" class="block text-sm font-semibold">Tanggal kunjungan<input type="date" name="visit_date" :required="type === 'tour'" min="{{ date('Y-m-d') }}" value="{{ old('visit_date') }}" class="mt-2 w-full rounded-xl border-sage-border"></label>
<label class="block text-sm font-semibold">Pesan<textarea name="message" required minlength="10" maxlength="5000" rows="4" class="mt-2 w-full rounded-xl border-sage-border focus:ring-forest">{{ old('message') }}</textarea></label>
<div class="hidden" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div>
<label class="flex items-start gap-3 text-xs leading-relaxed"><input type="checkbox" name="consent" value="1" required class="mt-1 rounded border-sage-border text-forest focus:ring-forest">Saya setuju data kontak ini digunakan untuk menindaklanjuti pesan dan kunjungan saya.</label>
<button type="submit" class="rounded-full bg-forest px-7 py-3 text-sm font-bold text-white transition hover:bg-forest-dark">Kirim Pesan →</button>
</form>
