<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
Schema::create('foundations', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable();  $table->timestamps(); });
Schema::create('schools', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable();  $table->timestamps(); });
Schema::create('pages', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete(); $table->timestamps(); });
Schema::create('news', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete(); $table->timestamps(); });
Schema::create('achievements', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete(); $table->timestamps(); });
Schema::create('facilities', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete(); $table->timestamps(); });
Schema::create('extracurriculars', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete(); $table->timestamps(); });
Schema::create('programs', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete(); $table->timestamps(); });
Schema::create('galleries', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete(); $table->timestamps(); });
Schema::create('admissions', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete(); $table->timestamps(); });
Schema::create('statistics', function (Blueprint $table) {
$table->id(); $table->string('title'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->longText('content')->nullable(); $table->string('image',2048)->nullable(); $table->string('status')->default('draft')->index(); $table->timestamp('published_at')->nullable()->index(); $table->unsignedInteger('sort_order')->default(0); $table->json('data')->nullable(); $table->string('meta_title')->nullable(); $table->text('meta_description')->nullable(); $table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete(); $table->timestamps(); });
 Schema::table('users',function(Blueprint $table){$table->string('role')->default('viewer');$table->foreignId('school_id')->nullable()->constrained()->restrictOnDelete();});
 foreach(['facility','extracurricular','program'] as $entity) {
 Schema::create($entity.'_school',function(Blueprint $table) use($entity){$table->id();$table->foreignId($entity.'_id')->constrained()->cascadeOnDelete();$table->foreignId('school_id')->constrained()->cascadeOnDelete();$table->unique([$entity.'_id','school_id']);});
 }
 Schema::create('inquiries',function(Blueprint $table){$table->id();$table->foreignId('school_id')->nullable()->constrained()->nullOnDelete();$table->string('type')->default('contact');$table->string('name');$table->string('email');$table->string('phone')->nullable();$table->text('message');$table->date('visit_date')->nullable();$table->string('status')->default('new');$table->timestamps();});
 Schema::create('subscribers',function(Blueprint $table){$table->id();$table->string('email')->unique();$table->timestamp('consented_at');$table->timestamps();});
 }
 public function down(): void {
 Schema::dropIfExists('subscribers');Schema::dropIfExists('inquiries');
 foreach(['facility','extracurricular','program'] as $entity) Schema::dropIfExists($entity.'_school');
 Schema::table('users',function(Blueprint $table){$table->dropConstrainedForeignId('school_id');$table->dropColumn('role');});
Schema::dropIfExists('statistics');Schema::dropIfExists('admissions');Schema::dropIfExists('galleries');Schema::dropIfExists('programs');Schema::dropIfExists('extracurriculars');Schema::dropIfExists('facilities');Schema::dropIfExists('achievements');Schema::dropIfExists('news');Schema::dropIfExists('pages');Schema::dropIfExists('schools');Schema::dropIfExists('foundations'); }
};
