@extends('layouts.public')
@section('content')
<main id="main-content" class="mx-auto max-w-7xl px-5 pb-20 pt-32 md:px-10"><a href="/ppdb" class="text-sm text-secondary">← Semua jenjang PPDB</a><div class="mt-8 grid gap-12 lg:grid-cols-[1.3fr_1fr]"><div><span class="rounded-full bg-lime px-4 py-1 text-xs font-bold text-forest">{{ data_get($item->data,'academic_year') }}</span><h1 class="mt-6 font-serif text-4xl leading-tight text-primary md:text-6xl">{{ $item->title }}</h1><p class="mt-6 text-secondary">{{ $item->description }}</p><dl class="mt-8 grid gap-4 rounded-3xl bg-surface-container-low p-6 sm:grid-cols-2">@foreach(['registration_start'=>'Mulai pendaftaran','registration_end'=>'Akhir pendaftaran','quota'=>'Kuota','selection_date'=>'Jadwal seleksi','announcement_date'=>'Pengumuman'] as $field=>$label)@if(data_get($item->data,$field))<div><dt class="text-xs uppercase tracking-wider text-secondary">{{ $label }}</dt><dd class="mt-2 font-semibold">{{ data_get($item->data,$field) }}</dd></div>@endif @endforeach</dl>
@foreach(['requirements'=>'Persyaratan','documents'=>'Dokumen yang diperlukan','stages'=>'Tahapan pendaftaran'] as $field=>$label)<section class="mt-10"><h2 class="font-serif text-3xl text-primary">{{ $label }}</h2><p class="mt-4 whitespace-pre-line leading-relaxed text-secondary">{{ data_get($item->data,$field) }}</p></section>@endforeach</div>
<aside class="h-fit rounded-[2rem] bg-forest p-8 text-white lg:sticky lg:top-28"><h2 class="font-serif text-3xl">Investasi Pendidikan</h2>@if(data_get($item->data,'publish_fees'))<dl class="mt-6 space-y-4">@foreach(['registration_fee'=>'Pendaftaran','entrance_fee'=>'Uang pangkal','tuition_fee'=>'SPP bulanan'] as $field=>$label)<div class="flex justify-between gap-4 border-b border-white/20 pb-3"><dt>{{ $label }}</dt><dd>Rp {{ number_format(data_get($item->data,$field,0),0,',','.') }}</dd></div>@endforeach</dl><p class="mt-4 whitespace-pre-line text-sm">{{ data_get($item->data,'other_fees') }}</p>@else<p class="mt-6 leading-relaxed text-white/80">Hubungi Admin PPDB untuk informasi biaya pendidikan dan ketersediaan tempat.</p>@endif
@if(data_get($item->data,'registration_url'))<a href="{{ data_get($item->data,'registration_url') }}" rel="noopener noreferrer" class="mt-8 flex justify-between rounded-full bg-lime px-6 py-3 font-bold text-forest">Daftar {{ $unit->data['level'] }} <span>↗</span></a>@endif
@if(data_get($item->data,'contact'))<a href="https://wa.me/{{ preg_replace('/\D/','',data_get($item->data,'contact')) }}" class="mt-4 block rounded-full border border-white/40 px-6 py-3 text-center">Hubungi Admin PPDB</a>@endif
@if(data_get($item->data,'brochure'))<a href="{{ \App\Models\Content::mediaUrl($item->data['brochure']) }}" class="mt-5 block text-center underline">Unduh brosur PDF</a>@endif
<p class="mt-6 text-xs leading-relaxed text-white/70">Pendaftaran dilanjutkan melalui kanal resmi yang ditentukan sekolah.</p></aside></div></main>
@endsection
