@extends('layouts.public')
@section('content')
<main id="main-content" class="mx-auto max-w-5xl px-5 pb-20 pt-32 md:px-10"><a href="/{{ $kind === 'program' ? 'akademik' : $kind }}" class="text-sm text-secondary">← Kembali ke koleksi</a><header class="py-8 md:py-12"><p class="mb-5 text-xs font-bold uppercase tracking-widest text-secondary">{{ $item->school?->title ?? 'Yayasan Harapan Mulia' }} · {{ data_get($item->data,'category') }}</p><h1 class="font-serif text-4xl leading-tight text-primary md:text-6xl">{{ $item->title }}</h1><p class="mt-6 text-lg leading-relaxed text-secondary">{{ $item->description }}</p>@if($kind==='berita')<p class="mt-5 text-sm text-secondary">{{ data_get($item->data,'author') }} · {{ $item->published_at?->translatedFormat('d F Y') }}</p>@endif</header>
@if($item->image)<img src="{{ $item->image_url }}" alt="{{ $item->title }}" class="mb-10 aspect-video w-full rounded-[2rem] object-cover" fetchpriority="high">@endif
<div class="grid gap-10 lg:grid-cols-[1fr_240px]"><article class="font-serif text-xl leading-relaxed text-on-surface-variant">@foreach(preg_split('/\n\s*\n/', $item->content ?? '') as $paragraph)<p class="mb-6 whitespace-pre-line">{{ $paragraph }}</p>@endforeach</article><aside class="h-fit space-y-5 rounded-2xl bg-surface-container-low p-6 text-sm">@foreach(['student_name'=>'Siswa / Tim','competition'=>'Kompetisi','organizer'=>'Penyelenggara','rank'=>'Juara','level'=>'Tingkat','year'=>'Tahun','location'=>'Lokasi','hours'=>'Jam operasional','curriculum'=>'Kurikulum','evaluation'=>'Evaluasi','schedule'=>'Jadwal','date'=>'Tanggal'] as $field=>$label)@if(data_get($item->data,$field))<div><h2 class="text-xs uppercase text-secondary">{{ $label }}</h2><p class="mt-1 whitespace-pre-line">{{ data_get($item->data,$field) }}</p></div>@endif @endforeach<a href="/ppdb" class="block rounded-full bg-forest px-4 py-3 text-center font-bold text-white">Informasi PPDB →</a></aside></div>
@if(data_get($item->data,'specifications'))<section class="mt-10 rounded-2xl bg-sage p-8"><h2 class="font-serif text-3xl">Spesifikasi Fasilitas</h2><p class="mt-5 whitespace-pre-line">{{ $item->data['specifications'] }}</p></section>@endif
@if($kind==='galeri')<div class="mt-10 grid grid-cols-2 gap-4 md:grid-cols-3">@foreach(data_get($item->data,'photos',data_get($item->data,'images',[])) as $photo)<button @click="lightbox = @js(\App\Models\Content::mediaUrl($photo))" aria-label="Perbesar foto" class="overflow-hidden rounded-2xl"><img src="{{ \App\Models\Content::mediaUrl($photo) }}" alt="{{ $item->title }}" loading="lazy" class="aspect-square w-full object-cover transition hover:scale-105"></button>@endforeach</div>@if(data_get($item->data,'video_url'))<a href="{{ $item->data['video_url'] }}" rel="noopener noreferrer" class="mt-6 inline-flex rounded-full bg-forest px-6 py-3 text-white">Tonton video ↗</a>@endif @endif
</main>
@endsection
